# Generated by Django 5.2.5 on 2025-08-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(max_length=100)),
                ('dia', models.DateField()),
                ('numero_reporte', models.CharField(max_length=50, unique=True)),
                ('coordinador', models.CharField(max_length=100)),
                ('encargado_cuadrilla', models.CharField(max_length=100)),
                ('parques_comunitarios', models.IntegerField(default=0)),
                ('parques_municipales', models.IntegerField(default=0)),
                ('otros', models.TextField(blank=True, null=True)),
                ('superficie_atendida_m2', models.IntegerField(default=0)),
                ('cesped_cortado_m2', models.IntegerField(default=0)),
                ('deshierbe_m2', models.IntegerField(default=0)),
                ('arboles_plantados', models.IntegerField(default=0)),
                ('arboles_podados', models.IntegerField(default=0)),
                ('arboles_retirados', models.IntegerField(default=0)),
                ('zacate_basura_kilos', models.IntegerField(default=0)),
                ('escombro_kilos', models.IntegerField(default=0)),
                ('llantas_recolectadas', models.IntegerField(default=0)),
                ('papeleo_m2', models.IntegerField(default=0)),
                ('personal_trabajo', models.IntegerField(default=0)),
                ('equipo_utilizado', models.TextField(blank=True, null=True)),
                ('material_utilizado', models.TextField(blank=True, null=True)),
                ('vehiculos_utilizados', models.TextField(blank=True, null=True)),
                ('necesita_reforestacion', models.BooleanField(default=False)),
                ('pintura_juegos', models.CharField(blank=True, choices=[('MALO', 'Malo'), ('REGULAR', 'Regular'), ('BUENO', 'Bueno'), ('EXCELENTE', 'Excelente')], max_length=20, null=True)),
                ('cuenta_jueguitos', models.BooleanField(default=False)),
                ('cuenta_mobiliario', models.BooleanField(default=False)),
                ('cuenta_sistema_riego', models.BooleanField(default=False)),
                ('cuenta_alumbrado', models.BooleanField(default=False)),
                ('observaciones_parque', models.TextField(blank=True, null=True)),
                ('otras_observaciones', models.TextField(blank=True, null=True)),
                ('pendientes', models.TextField(blank=True, null=True)),
                ('ubicacion_area', models.CharField(blank=True, max_length=200, null=True)),
                ('colonia_camellon', models.CharField(blank=True, max_length=200, null=True)),
                ('calle', models.CharField(blank=True, max_length=200, null=True)),
                ('monumentos_atendidos', models.IntegerField(default=0)),
                ('camellones_atendidos', models.IntegerField(default=0)),
                ('trabajo_diario', models.BooleanField(default=False)),
                ('trabajo_ciudadania', models.BooleanField(default=False)),
                ('operativo_especial', models.BooleanField(default=False)),
                ('frecuencia_basura', models.CharField(blank=True, choices=[('NUNCA', 'Nunca'), ('1', '1 vez por semana'), ('2', '2 veces por semana'), ('3', '3 veces por semana')], max_length=50, null=True)),
            ],
        ),
    ]
