# Generated by Django 5.2.5 on 2025-08-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportecuadrilla',
            name='fecha',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='dia',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
