# Generated by Django 5.2.5 on 2025-08-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_reportecuadrilla_fecha_alter_reportecuadrilla_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportecuadrilla',
            name='apoyo_areas_gob',
            field=models.IntegerField(default=0),
        ),
    ]
