# Generated by Django 5.2.5 on 2025-08-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_reportecuadrilla_apoyo_areas_gob'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportecuadrilla',
            name='trabajo_realizado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
