# Generated by Django 5.2.5 on 2025-08-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0004_reportecuadrilla_trabajo_realizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportecuadrilla',
            name='frecuncia_recoleccion_basura',
            field=models.CharField(blank=True, choices=[('1', '1 VEZ POR SEMANA'), ('2', '2 VECES POR SEMANA'), ('3', '3 VECES POR SEMANA'), ('0', 'NUNCA')], max_length=25),
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='cuenta_alumbrado',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('MALO', 'Malo'), ('REGULAR', 'Regular'), ('BUENO', 'Bueno'), ('EXCELENTE', 'Excelente')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='cuenta_jueguitos',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('MALO', 'Malo'), ('REGULAR', 'Regular'), ('BUENO', 'Bueno'), ('EXCELENTE', 'Excelente')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='cuenta_mobiliario',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('MALO', 'Malo'), ('REGULAR', 'Regular'), ('BUENO', 'Bueno'), ('EXCELENTE', 'Excelente')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='cuenta_sistema_riego',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('MALO', 'Malo'), ('REGULAR', 'Regular'), ('BUENO', 'Bueno'), ('EXCELENTE', 'Excelente')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='necesita_reforestacion',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('MALO', 'Malo'), ('REGULAR', 'Regular'), ('BUENO', 'Bueno'), ('EXCELENTE', 'Excelente')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='pintura_juegos',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('MALO', 'Malo'), ('REGULAR', 'Regular'), ('BUENO', 'Bueno'), ('EXCELENTE', 'Excelente')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
