# Generated by Django 5.2.5 on 2025-08-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_reportecuadrilla_frecuncia_recoleccion_basura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportecuadrilla',
            name='frecuencia_basura',
        ),
    ]
