# Generated by Django 5.2.5 on 2025-08-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0006_remove_reportecuadrilla_frecuencia_basura'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportecuadrilla',
            name='otros_cant',
            field=models.TextField(blank=True, null=True),
        ),
    ]
