# Generated by Django 5.2.5 on 2025-08-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0007_reportecuadrilla_otros_cant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='otros',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='otros_cant',
            field=models.IntegerField(default=0),
        ),
    ]
