# Generated by Django 5.2.5 on 2025-08-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0008_alter_reportecuadrilla_otros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportecuadrilla',
            name='numero_reporte',
        ),
    ]
