# Generated by Django 5.2.5 on 2025-08-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0009_remove_reportecuadrilla_numero_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='apoyo_areas_gob',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='camellones_atendidos',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='monumentos_atendidos',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='otros_cant',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='parques_comunitarios',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='parques_municipales',
            field=models.BooleanField(default=0),
        ),
    ]
