# Generated by Django 5.2.5 on 2025-09-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0010_alter_reportecuadrilla_apoyo_areas_gob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteChamizal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('trabajo_diario', models.BooleanField(default=False)),
                ('trabajo_ciudadania', models.BooleanField(default=False)),
                ('operativo_especial', models.BooleanField(default=False)),
                ('coordinador', models.CharField(max_length=100)),
                ('encargado_cuadrilla', models.CharField(max_length=100)),
                ('parque_chamizal', models.BooleanField(default=False)),
                ('hoyos', models.BooleanField(default=False)),
                ('camellones', models.BooleanField(default=False)),
                ('otros', models.CharField(blank=True, max_length=20, null=True)),
                ('otros_bool', models.BooleanField(default=False)),
                ('superficie_atendida_m2', models.IntegerField(default=0)),
                ('cesped_cortado_m2', models.IntegerField(default=0)),
                ('deshierbe_m2', models.IntegerField(default=0)),
                ('arboles_plantados', models.IntegerField(default=0)),
                ('arboles_podados', models.IntegerField(default=0)),
                ('arboles_retirados', models.IntegerField(default=0)),
                ('zacate_basura_kilos', models.IntegerField(default=0)),
                ('papeleo_m2', models.IntegerField(default=0)),
                ('personal_trabajo', models.IntegerField(default=0)),
                ('trabajo_realizado', models.TextField(blank=True, null=True)),
                ('pendientes', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ubicacion_area', models.CharField(blank=True, max_length=200, null=True)),
                ('equipo_utilizado', models.TextField(blank=True, null=True)),
                ('material_utilizado', models.TextField(blank=True, null=True)),
                ('vehiculos_utilizados', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
