# Generated by Django 5.2.5 on 2025-09-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0011_reportechamizal'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportechamizal',
            name='dia',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
