# Generated by Django 5.2.5 on 2025-09-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0012_reportechamizal_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dia', models.CharField(blank=True, max_length=20)),
                ('encargado', models.CharField(blank=True, max_length=100)),
                ('lugar', models.CharField(blank=True, max_length=100)),
                ('personas_beneficiadas', models.IntegerField(default=0)),
                ('escuela_atendida', models.CharField(blank=True, max_length=100)),
                ('maquiladora_atendida', models.CharField(blank=True, max_length=100)),
                ('platica_sustentabilidad', models.CharField(blank=True, max_length=100)),
                ('curso_poda', models.CharField(blank=True, max_length=100)),
                ('comite_parque', models.CharField(blank=True, max_length=100)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('calle1', models.CharField(blank=True, max_length=100)),
                ('calle2', models.CharField(blank=True, max_length=100)),
                ('calle3', models.CharField(blank=True, max_length=100)),
                ('calle4', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('nombre_ciudadano', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
