# Generated by Django 5.2.5 on 2025-09-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0013_reportecultura'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dia', models.CharField(blank=True, max_length=20)),
                ('coordinador', models.CharField(blank=True, max_length=100)),
                ('encargado', models.CharField(blank=True, max_length=100)),
                ('superficie_atendida_m2', models.IntegerField(default=0)),
                ('limpieza_papeleo_m2', models.IntegerField(default=0)),
                ('reparacion_tuberia', models.IntegerField(default=0)),
                ('basura_kg', models.IntegerField(default=0)),
                ('reparacion_bomba', models.IntegerField(default=0)),
                ('instalacion_bomba', models.IntegerField(default=0)),
                ('personal_trabajo', models.IntegerField(default=0)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('calle1', models.CharField(blank=True, max_length=100)),
                ('calle2', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
