# Generated by Django 5.2.5 on 2025-09-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0014_reportefuentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('dia', models.CharField(blank=True, max_length=20)),
                ('trabajo_diario', models.BooleanField(default=False)),
                ('trabajo_ciudadania', models.BooleanField(default=False)),
                ('operativo_especial', models.BooleanField(default=False)),
                ('coordinador', models.CharField(max_length=100)),
                ('encargado_cuadrilla', models.CharField(max_length=100)),
                ('parques_comunitarios', models.BooleanField(default=0)),
                ('parques_municipales', models.BooleanField(default=0)),
                ('monumentos_atendidos', models.BooleanField(default=0)),
                ('camellones_atendidos', models.BooleanField(default=0)),
                ('apoyo_areas_gob', models.BooleanField(default=0)),
                ('otros_cant', models.BooleanField(default=0)),
                ('superficie_atendida_m2', models.IntegerField(default=0)),
                ('reparacion_fugas', models.IntegerField(default=0)),
                ('instalacion_agua', models.IntegerField(default=0)),
                ('instalacion_riego', models.IntegerField(default=0)),
                ('revision_riego', models.IntegerField(default=0)),
                ('material_riego', models.IntegerField(default=0)),
                ('otros', models.IntegerField(default=0)),
                ('personal_trabajo', models.IntegerField(default=0)),
                ('trabajo_realizado', models.TextField(blank=True, null=True)),
                ('pendientes', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('calle1', models.CharField(blank=True, max_length=100)),
                ('calle2', models.CharField(blank=True, max_length=100)),
                ('equipo_utilizado', models.TextField(blank=True, null=True)),
                ('material_utilizado', models.TextField(blank=True, null=True)),
                ('vehiculos_utilizados', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
