# Generated by Django 5.2.5 on 2025-09-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0015_reportefugas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefugas',
            name='otros',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
