# Generated by Django 5.2.5 on 2025-09-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0016_alter_reportefugas_otros'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportePintura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dia', models.CharField(blank=True, max_length=20)),
                ('distrito', models.CharField(max_length=100)),
                ('encargado', models.CharField(blank=True, max_length=100)),
                ('coordinador', models.CharField(blank=True, max_length=100)),
                ('trabajo_diario', models.BooleanField(default=False)),
                ('trabajo_ciudadania', models.BooleanField(default=False)),
                ('operativo_especial', models.BooleanField(default=False)),
                ('comunitarios_atendidos', models.IntegerField(default=0)),
                ('municipales_atendidos', models.IntegerField(default=0)),
                ('monumentos_atendidos', models.IntegerField(default=0)),
                ('camellones_atendidos', models.IntegerField(default=0)),
                ('apoyo_areas_gob', models.IntegerField(default=0)),
                ('otros', models.CharField(blank=True, max_length=20, null=True)),
                ('otros_cant', models.BooleanField(default=0)),
                ('superficie_atendida_m2', models.IntegerField(default=0)),
                ('bancas_cemento', models.IntegerField(default=0)),
                ('bancas_metalicas', models.IntegerField(default=0)),
                ('multijuegos', models.IntegerField(default=0)),
                ('resvaladeros', models.IntegerField(default=0)),
                ('sube_y_baja', models.IntegerField(default=0)),
                ('columpios', models.IntegerField(default=0)),
                ('pasamanos', models.IntegerField(default=0)),
                ('juego_esferas', models.IntegerField(default=0)),
                ('canchas', models.IntegerField(default=0)),
                ('porterias', models.IntegerField(default=0)),
                ('encalado_arboles', models.IntegerField(default=0)),
                ('levantado_malla', models.IntegerField(default=0)),
                ('reposicion_malla', models.IntegerField(default=0)),
                ('pintura_utilizada_litros', models.IntegerField(default=0)),
                ('thinner_utilizado_litros', models.IntegerField(default=0)),
                ('personal_trabajo', models.IntegerField(default=0)),
                ('trabajo_realizado', models.TextField(blank=True, null=True)),
                ('pendientes', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('calle1', models.CharField(blank=True, max_length=100)),
                ('calle2', models.CharField(blank=True, max_length=100)),
                ('equipo_utilizado', models.TextField(blank=True, null=True)),
                ('material_utilizado', models.TextField(blank=True, null=True)),
                ('vehiculos_utilizados', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
