# Generated by Django 5.2.5 on 2025-09-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0017_reportepintura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportepintura',
            name='apoyo_areas_gob',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='reportepintura',
            name='camellones_atendidos',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='reportepintura',
            name='comunitarios_atendidos',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='reportepintura',
            name='monumentos_atendidos',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='reportepintura',
            name='municipales_atendidos',
            field=models.BooleanField(default=0),
        ),
    ]
