# Generated by Django 5.2.5 on 2025-09-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0018_alter_reportepintura_apoyo_areas_gob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportepintura',
            old_name='sube_y_baja',
            new_name='sube_baja',
        ),
    ]
