# Generated by Django 5.2.5 on 2025-09-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0019_rename_sube_y_baja_reportepintura_sube_baja'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteRiegoChamizal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riego_en', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('dia', models.CharField(blank=True, max_length=20)),
                ('encargado', models.CharField(blank=True, max_length=100)),
                ('superficie_atendida_m2', models.IntegerField(default=0)),
                ('reparacion_fugas', models.IntegerField(default=0)),
                ('limpieza_aspersores', models.IntegerField(default=0)),
                ('basura_recolectada', models.IntegerField(default=0)),
                ('papel_m2', models.IntegerField(default=0)),
                ('personal_trabajo', models.IntegerField(default=0)),
                ('ubicacion_area', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
