# Generated by Django 5.2.5 on 2025-09-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0020_reporteriegochamizal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteRiegoPipas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dia', models.CharField(blank=True, max_length=20)),
                ('nombre_chofer', models.CharField(blank=True, max_length=100)),
                ('nombre_ayudante', models.CharField(blank=True, max_length=100)),
                ('engomado_vehiculo', models.CharField(blank=True, max_length=100)),
                ('hora_salida', models.TimeField()),
                ('hora_regreso', models.TimeField()),
                ('lugar_riego', models.CharField(blank=True, max_length=100)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('calle1', models.CharField(blank=True, max_length=100)),
                ('calle2', models.CharField(blank=True, max_length=100)),
                ('viajes', models.IntegerField(default=0)),
                ('agua_empleada_litros', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
