# Generated by Django 5.2.5 on 2025-09-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0021_reporteriegopipas'),
    ]

    operations = [
    ]
