# Generated by Django 5.2.5 on 2025-09-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0022_auto_20250929_1104'),
    ]

    operations = [
    ]
