# Generated by Django 5.2.5 on 2025-09-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0024_auto_20250929_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportecuadrilla',
            name='no_reporte',
            field=models.IntegerField(default=1),
        ),
    ]
