# Generated by Django 5.2.5 on 2025-09-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0025_reportecuadrilla_no_reporte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportecuadrilla',
            old_name='no_reporte',
            new_name='folio_pac',
        ),
    ]
