# Generated by Django 5.2.5 on 2025-09-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0026_rename_no_reporte_reportecuadrilla_folio_pac'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportechamizal',
            name='folio_pac',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reportecultura',
            name='folio_pac',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reportefuentes',
            name='folio_pac',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reportefugas',
            name='folio_pac',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reportepintura',
            name='folio_pac',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reporteriegochamizal',
            name='folio_pac',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reporteriegopipas',
            name='folio_pac',
            field=models.IntegerField(default=1),
        ),
    ]
