# Generated by Django 5.2.5 on 2025-10-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0027_reportechamizal_folio_pac_reportecultura_folio_pac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='calle',
            field=models.CharField(default='X', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='colonia_camellon',
            field=models.CharField(default='X', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='dia',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='equipo_utilizado',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='material_utilizado',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='pendientes',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='trabajo_realizado',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='ubicacion_area',
            field=models.CharField(default='X', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='vehiculos_utilizados',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
    ]
