# Generated by Django 5.2.5 on 2025-10-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0028_alter_reportecuadrilla_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportechamizal',
            name='folio_pac',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='folio_pac',
            field=models.IntegerField(),
        ),
    ]
