# Generated by Django 5.2.5 on 2025-10-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0029_alter_reportechamizal_folio_pac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportechamizal',
            name='equipo_utilizado',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportechamizal',
            name='material_utilizado',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportechamizal',
            name='observaciones',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportechamizal',
            name='pendientes',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportechamizal',
            name='trabajo_realizado',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportechamizal',
            name='ubicacion_area',
            field=models.CharField(default='X'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportechamizal',
            name='vehiculos_utilizados',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
    ]
