# Generated by Django 5.2.5 on 2025-10-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0030_alter_reportechamizal_equipo_utilizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecultura',
            name='calle1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportecultura',
            name='calle2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportecultura',
            name='calle3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportecultura',
            name='calle4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportecultura',
            name='colonia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportecultura',
            name='comite_parque',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportecultura',
            name='curso_poda',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportecultura',
            name='escuela_atendida',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportecultura',
            name='maquiladora_atendida',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportecultura',
            name='nombre_ciudadano',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportecultura',
            name='observaciones',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportecultura',
            name='platica_sustentabilidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportecultura',
            name='responsable',
            field=models.CharField(max_length=100),
        ),
    ]
