# Generated by Django 5.2.5 on 2025-10-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0031_alter_reportecultura_calle1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecultura',
            name='nombre_ciudadano',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reportecultura',
            name='responsable',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
