# Generated by Django 5.2.5 on 2025-10-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0032_alter_reportecultura_nombre_ciudadano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecultura',
            name='dia',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reportecultura',
            name='encargado',
            field=models.CharField(max_length=100),
        ),
    ]
