# Generated by Django 5.2.5 on 2025-10-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0033_alter_reportecultura_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecultura',
            name='lugar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportefuentes',
            name='calle1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportefuentes',
            name='calle2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportefuentes',
            name='colonia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportefuentes',
            name='coordinador',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportefuentes',
            name='dia',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reportefuentes',
            name='encargado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportefuentes',
            name='folio_pac',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reportefuentes',
            name='observaciones',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
