# Generated by Django 5.2.5 on 2025-10-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0034_alter_reportecultura_lugar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefugas',
            name='calle1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportefugas',
            name='calle2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportefugas',
            name='colonia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportefugas',
            name='equipo_utilizado',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportefugas',
            name='material_utilizado',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportefugas',
            name='observaciones',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportefugas',
            name='pendientes',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportefugas',
            name='trabajo_realizado',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportefugas',
            name='vehiculos_utilizados',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
    ]
