# Generated by Django 5.2.5 on 2025-10-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0035_alter_reportefugas_calle1_alter_reportefugas_calle2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportepintura',
            name='folio_pac',
            field=models.IntegerField(),
        ),
    ]
