# Generated by Django 5.2.5 on 2025-10-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0036_alter_reportepintura_folio_pac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefugas',
            name='dia',
            field=models.CharField(max_length=20),
        ),
    ]
