# Generated by Django 5.2.5 on 2025-10-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0037_alter_reportefugas_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefugas',
            name='folio_pac',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reportefugas',
            name='superficie_atendida_m2',
            field=models.IntegerField(),
        ),
    ]
