# Generated by Django 5.2.5 on 2025-10-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0039_alter_reportechamizal_arboles_plantados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecultura',
            name='folio_pac',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reporteriegochamizal',
            name='folio_pac',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reporteriegopipas',
            name='folio_pac',
            field=models.IntegerField(),
        ),
    ]
