# Generated by Django 5.2.5 on 2025-10-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0040_alter_reportecultura_folio_pac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='folio_pac',
            field=models.IntegerField(blank=True),
        ),
    ]
