# Generated by Django 5.2.5 on 2025-10-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0041_alter_reportecuadrilla_folio_pac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='folio_pac',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
