# Generated by Django 5.2.5 on 2025-10-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0043_alter_reportefugas_folio_pac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportechamizal',
            name='folio_pac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportecultura',
            name='folio_pac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportefuentes',
            name='folio_pac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportepintura',
            name='folio_pac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporteriegochamizal',
            name='folio_pac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporteriegopipas',
            name='folio_pac',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
