# Generated by Django 5.2.5 on 2025-10-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0045_alter_reportepintura_calle1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteriegopipas',
            name='folio_pac',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
