# Generated by Django 5.2.5 on 2025-10-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0047_alter_reportecultura_folio_pac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefuentes',
            name='folio_pac',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
