# Generated by Django 5.2.5 on 2025-10-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0048_alter_reportefuentes_folio_pac'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportecuadrilla',
            name='operativo_comentarios',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
