# Generated by Django 5.2.5 on 2025-10-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0050_alter_reportecuadrilla_operativo_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecuadrilla',
            name='operativo_comentarios',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
