# Generated by Django 5.2.5 on 2025-10-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0052_alter_reportecuadrilla_operativo_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportechamizal',
            name='operativo_comentarios',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='reportefugas',
            name='operativo_comentarios',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='reportepintura',
            name='operativo_comentarios',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
