# Generated by Django 5.2.5 on 2025-11-03 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0054_reportesoldadura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportechamizal',
            name='creador_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportechamizal',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/antes/'),
        ),
        migrations.AddField(
            model_name='reportechamizal',
            name='foto_despues',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/despues/'),
        ),
        migrations.AddField(
            model_name='reportecuadrilla',
            name='creador_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportecuadrilla',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/antes/'),
        ),
        migrations.AddField(
            model_name='reportecuadrilla',
            name='foto_despues',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/despues/'),
        ),
        migrations.AddField(
            model_name='reportecultura',
            name='creador_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportecultura',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/antes/'),
        ),
        migrations.AddField(
            model_name='reportecultura',
            name='foto_despues',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/despues/'),
        ),
        migrations.AddField(
            model_name='reportefuentes',
            name='creador_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportefuentes',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/antes/'),
        ),
        migrations.AddField(
            model_name='reportefuentes',
            name='foto_despues',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/despues/'),
        ),
        migrations.AddField(
            model_name='reportefugas',
            name='creador_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportefugas',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/antes/'),
        ),
        migrations.AddField(
            model_name='reportefugas',
            name='foto_despues',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/despues/'),
        ),
        migrations.AddField(
            model_name='reportepintura',
            name='creador_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportepintura',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/antes/'),
        ),
        migrations.AddField(
            model_name='reportepintura',
            name='foto_despues',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/despues/'),
        ),
        migrations.AddField(
            model_name='reporteriegochamizal',
            name='creador_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporteriegochamizal',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/antes/'),
        ),
        migrations.AddField(
            model_name='reporteriegochamizal',
            name='foto_despues',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/despues/'),
        ),
        migrations.AddField(
            model_name='reporteriegopipas',
            name='creador_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporteriegopipas',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/antes/'),
        ),
        migrations.AddField(
            model_name='reporteriegopipas',
            name='foto_despues',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/despues/'),
        ),
        migrations.AddField(
            model_name='reportesoldadura',
            name='creador_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportesoldadura',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/antes/'),
        ),
        migrations.AddField(
            model_name='reportesoldadura',
            name='foto_despues',
            field=models.ImageField(blank=True, null=True, upload_to='reporte/fotos/despues/'),
        ),
    ]
