# Generated by Django 5.2.5 on 2025-11-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0057_alter_reportechamizal_creador_por_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportechamizal',
            old_name='creador_por',
            new_name='creado_por',
        ),
        migrations.RenameField(
            model_name='reportecuadrilla',
            old_name='creador_por',
            new_name='creado_por',
        ),
        migrations.RenameField(
            model_name='reportecultura',
            old_name='creador_por',
            new_name='creado_por',
        ),
        migrations.RenameField(
            model_name='reportefuentes',
            old_name='creador_por',
            new_name='creado_por',
        ),
        migrations.RenameField(
            model_name='reportefugas',
            old_name='creador_por',
            new_name='creado_por',
        ),
        migrations.RenameField(
            model_name='reportepintura',
            old_name='creador_por',
            new_name='creado_por',
        ),
        migrations.RenameField(
            model_name='reporteriegochamizal',
            old_name='creador_por',
            new_name='creado_por',
        ),
        migrations.RenameField(
            model_name='reporteriegopipas',
            old_name='creador_por',
            new_name='creado_por',
        ),
        migrations.RenameField(
            model_name='reportesoldadura',
            old_name='creador_por',
            new_name='creado_por',
        ),
    ]
