# Generated by Django 5.2.5 on 2025-12-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0058_rename_creador_por_reportechamizal_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportecuadrilla',
            name='estatus',
            field=models.CharField(choices=[('0', 'Verde'), ('1', 'Rojo')], default='0', max_length=1),
        ),
    ]
