# Generated by Django 5.2.5 on 2025-12-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0059_reportecuadrilla_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportechamizal',
            name='estatus',
            field=models.CharField(choices=[('0', 'Verde'), ('1', 'Rojo')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='reportecultura',
            name='estatus',
            field=models.CharField(choices=[('0', 'Verde'), ('1', 'Rojo')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='reportefuentes',
            name='estatus',
            field=models.CharField(choices=[('0', 'Verde'), ('1', 'Rojo')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='reportefugas',
            name='estatus',
            field=models.CharField(choices=[('0', 'Verde'), ('1', 'Rojo')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='reportepintura',
            name='estatus',
            field=models.CharField(choices=[('0', 'Verde'), ('1', 'Rojo')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='reporteriegochamizal',
            name='estatus',
            field=models.CharField(choices=[('0', 'Verde'), ('1', 'Rojo')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='reporteriegopipas',
            name='estatus',
            field=models.CharField(choices=[('0', 'Verde'), ('1', 'Rojo')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='reportesoldadura',
            name='estatus',
            field=models.CharField(choices=[('0', 'Verde'), ('1', 'Rojo')], default='0', max_length=1),
        ),
    ]
