# Generated by Django 5.2.5 on 2025-09-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariosinfo',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
